/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package uas.pbo;

import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ASUS
 */
public class admin extends javax.swing.JFrame {
 private void kosong_kolom(){
        txtantrian.setText(null);
        txtnama.setText(null);
        txtno.setText(null);
        txtbarber.setText(null);

    }
    
    private void tampil_data(){
        DefaultTableModel model = new DefaultTableModel();
        model.addColumn("No. ");
        model.addColumn("Nama");
        model.addColumn("No Hp");
        model.addColumn("Barber Man");
    
        try{
            int no = 1;
            String sql = "SELECT * FROM pelanggan";
            java.sql.Connection conn = (Connection)UASPBO.configDB();
            java.sql.Statement stm = conn.createStatement();
            java.sql.ResultSet res = stm.executeQuery(sql);
            
            while(res.next()){
                model.addRow(new Object[]{res.getString(1),res.getString(2),
                                                res.getString(3),
                                                res.getString(4)});
            }
            tablehair.setModel(model);
            
        }catch(SQLException e){
            System.out.println("Eror : " + e.getMessage());
        }
    }

    public admin() {
        initComponents();
        kosong_kolom();
        tampil_data();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        txtno = new javax.swing.JTextField();
        txtbarber = new javax.swing.JTextField();
        txtnama = new javax.swing.JTextField();
        txtantrian = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablehair = new javax.swing.JTable();
        hapus = new javax.swing.JButton();
        update = new javax.swing.JButton();
        tambah = new javax.swing.JButton();
        barberman = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(153, 204, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnoActionPerformed(evt);
            }
        });
        jPanel2.add(txtno, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 120, 179, 33));
        jPanel2.add(txtbarber, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 170, 179, 33));
        jPanel2.add(txtnama, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 70, 179, 33));
        jPanel2.add(txtantrian, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 20, 179, 33));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel1.setText("Id Barberman");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 170, 130, 30));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel2.setText("No Antrian");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 20, 130, 30));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel3.setText("Nama");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 70, 130, 30));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel4.setText("No Hp");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 120, 130, 30));

        tablehair = new javax.swing.JTable(){
            public boolean isCellEdittable(int rowIndex, int colIndex){
                return false;
            }
        };
        tablehair.getTableHeader().setReorderingAllowed(false);
        tablehair.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tablehair);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 280, 600, 110));

        hapus.setText("Hapus");
        hapus.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                hapusMouseClicked(evt);
            }
        });
        jPanel2.add(hapus, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 250, 75, -1));

        update.setText("Update");
        update.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                updateMouseClicked(evt);
            }
        });
        update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateActionPerformed(evt);
            }
        });
        jPanel2.add(update, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 250, 75, -1));

        tambah.setText("Tambah");
        tambah.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tambahMouseClicked(evt);
            }
        });
        tambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tambahActionPerformed(evt);
            }
        });
        jPanel2.add(tambah, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 250, 75, -1));

        barberman.setText("Barberman");
        barberman.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                barbermanMouseClicked(evt);
            }
        });
        jPanel2.add(barberman, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 250, 90, -1));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/images__1_-removebg-preview_1.png"))); // NOI18N
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, 233, 259));

        jLabel5.setFont(new java.awt.Font("Monotype Corsiva", 1, 24)); // NOI18N
        jLabel5.setText("FORBICE BARBERSHOP");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 240, 270, -1));

        jPanel2.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 290, 410));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 926, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnoActionPerformed

    private void tambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tambahActionPerformed
//    try{
//            String mysql = "INSERT INTO pelanggan VALUES ('"+txtantrian.getText()+"','"
//                                                           +txtnama.getText()+"','"
//                                                           +txtnohp.getText()+"','"
//                                                           +txtbarber.getText()+"')";
//            java.sql.Connection conn = (Connection)UASPBO.configDB();
//            java.sql.PreparedStatement pstm = conn.prepareStatement(mysql);
//            pstm.execute();
//            JOptionPane.showMessageDialog(null, "Data antrian haircut berhasil disimpan");
//        }catch(HeadlessException | SQLException e){
//            JOptionPane.showMessageDialog(this, e.getMessage());
//        }
//        tampil_data();
//        kosong_kolom();
    }//GEN-LAST:event_tambahActionPerformed

    private void updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateActionPerformed

//         try{
//            String mysql = "UPDATE pelanggan SET no_antrian='"+txtantrian.getText()+"',nama_p='"
//                                                         +txtnama.getText()+"',no_hp='"
//                                                         +txtnohp.getText()+"',id_barberm='"
//                                                         +txtbarber.getText()+"' WHERE no_antrian='"+txtantrian.getText()+"'";
//            java.sql.Connection conn = (Connection)UASPBO.configDB();
//            java.sql.PreparedStatement pstm = conn.prepareStatement(mysql);
//            pstm.execute();
//            JOptionPane.showMessageDialog(null, "Data antrian berhasil di perbarui");
//            kosong_kolom();
//        }catch(HeadlessException | SQLException e){
//            JOptionPane.showMessageDialog(this, e.getMessage());
//        }
//        tampil_data();
//    
    }//GEN-LAST:event_updateActionPerformed

    private void tambahMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tambahMouseClicked
       try{
            String mysql = "INSERT INTO pelanggan VALUES ('"+txtantrian.getText()+"','"
                                                           +txtnama.getText()+"','"
                                                           +txtno.getText()+"','"
                                                           +txtbarber.getText()+"')";
            java.sql.Connection conn = (Connection)UASPBO.configDB();
            java.sql.PreparedStatement pstm = conn.prepareStatement(mysql);
            pstm.execute();
            JOptionPane.showMessageDialog(null, "Data antrian haircut berhasil disimpan");
        }catch(HeadlessException | SQLException e){
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
        tampil_data();
        kosong_kolom();
      
    }//GEN-LAST:event_tambahMouseClicked

    private void updateMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_updateMouseClicked
     try{
            String mysql = "UPDATE pelanggan SET no_antrian='"+txtantrian.getText()+"',nama_p='"
                                                         +txtnama.getText()+"',no_hp='"
                                                         +txtno.getText()+"',id_barberm='"
                                                         +txtbarber.getText()+"' WHERE no_antrian='"+txtantrian.getText()+"'";
            java.sql.Connection conn = (Connection)UASPBO.configDB();
            java.sql.PreparedStatement pstm = conn.prepareStatement(mysql);
            pstm.execute();
            JOptionPane.showMessageDialog(null, "Data antrian berhasil di perbarui");
            kosong_kolom();
        }catch(HeadlessException | SQLException e){
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
        tampil_data();
    }//GEN-LAST:event_updateMouseClicked

    private void hapusMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_hapusMouseClicked
        try{
            String mysql = "DELETE FROM pelanggan WHERE no_antrian='"+txtantrian.getText()+"'";
            java.sql.Connection conn = (Connection)UASPBO.configDB();
            java.sql.PreparedStatement pstm = conn.prepareStatement(mysql);
            pstm.execute();
            JOptionPane.showMessageDialog(null, "Data antrian haircut berhasil dihapus");
        }catch(HeadlessException | SQLException e){
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
        tampil_data();
        kosong_kolom();
    }//GEN-LAST:event_hapusMouseClicked

    private void barbermanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_barbermanMouseClicked
         new barberman().show();
         this.dispose();
    }//GEN-LAST:event_barbermanMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new admin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton barberman;
    private javax.swing.JButton hapus;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tablehair;
    private javax.swing.JButton tambah;
    private javax.swing.JTextField txtantrian;
    private javax.swing.JTextField txtbarber;
    private javax.swing.JTextField txtnama;
    private javax.swing.JTextField txtno;
    private javax.swing.JButton update;
    // End of variables declaration//GEN-END:variables
}
